# Generated by Django 4.0.3 on 2022-05-09 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='anganawadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100, null=True)),
                ('a_pic', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('a_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('a_licenseno', models.CharField(max_length=100, null=True)),
                ('a_contact', models.CharField(max_length=100, null=True)),
                ('a_email', models.CharField(max_length=100, null=True)),
                ('a_username', models.CharField(max_length=100, null=True)),
                ('a_password', models.CharField(max_length=100, null=True)),
                ('a_confirmpsw', models.CharField(max_length=100, null=True)),
                ('a_status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='complainttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complainttype', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Districtofficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, null=True)),
                ('housename', models.CharField(max_length=100, null=True)),
                ('emil', models.CharField(max_length=100, null=True)),
                ('id_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('Image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('street', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirmpassword', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='foodtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='prooftype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pwomenfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_pic', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('pfood_amt', models.CharField(max_length=100, null=True)),
                ('pfood_duration', models.CharField(max_length=100, null=True)),
                ('pfood_name', models.CharField(max_length=100, null=True)),
                ('food_description', models.CharField(max_length=200, null=True)),
                ('dofficer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('foodtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_pic', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('food_name', models.CharField(max_length=100, null=True)),
                ('food_description', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('dofficer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('foodtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('emil', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=100, null=True)),
                ('id_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('place', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userfoodservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(max_length=100, null=True)),
                ('end_date', models.DateField(max_length=100, null=True)),
                ('active_status', models.CharField(max_length=100, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('anganwadi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300, null=True)),
                ('user_contact', models.CharField(max_length=300, null=True)),
                ('user_email', models.CharField(max_length=300, null=True)),
                ('user_username', models.CharField(max_length=300, null=True)),
                ('user_password', models.CharField(max_length=300, null=True)),
                ('usser_confirm', models.CharField(max_length=300, null=True)),
                ('user_housename', models.CharField(max_length=300, null=True)),
                ('user_street', models.CharField(max_length=300, null=True)),
                ('user_pincode', models.CharField(max_length=300, null=True)),
                ('user_certificate', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('user_age', models.CharField(max_length=300, null=True)),
                ('user_status', models.CharField(max_length=300, null=True)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location')),
                ('place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_totalpfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfood_totalStock', models.IntegerField(max_length=100, null=True)),
                ('pfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_totalfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_totalStock', models.IntegerField(null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_totalchildfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_totalStock', models.IntegerField(max_length=100, null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pwomens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwomen_name', models.CharField(max_length=300, null=True)),
                ('pwomen_husbandname', models.CharField(max_length=300, null=True)),
                ('pwomen_contact', models.CharField(max_length=300, null=True)),
                ('pwomen_medicalproof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('pwomen_photo', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('pwomen_email', models.CharField(max_length=300, null=True)),
                ('pwomen_isactive', models.CharField(max_length=300, null=True)),
                ('pwomen_username', models.CharField(max_length=300, null=True)),
                ('pwomen_pincode', models.CharField(max_length=300, null=True)),
                ('pwomen_password', models.CharField(max_length=300, null=True)),
                ('pwomen_confirmpassword', models.CharField(max_length=300, null=True)),
                ('p_street', models.CharField(max_length=300, null=True)),
                ('pwomen_age', models.CharField(max_length=300, null=True)),
                ('pwomen_house', models.CharField(max_length=300, null=True)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location')),
                ('place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pwomenfoodservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(max_length=100, null=True)),
                ('end_date', models.DateField(max_length=100, null=True)),
                ('active_status', models.CharField(max_length=100, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('anganwadi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfood')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pfoodstockrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsrequest_date', models.DateField(auto_now_add=True)),
                ('pquantity', models.IntegerField(null=True)),
                ('f_status', models.CharField(max_length=100, null=True)),
                ('dofficer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfood_stock', models.IntegerField(null=True)),
                ('pfoodstock_date', models.DateField(max_length=100, null=True)),
                ('pfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pfoodbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfoodbooking_date', models.DateField(auto_now_add=True)),
                ('pfoodbooking_status', models.CharField(max_length=300, null=True)),
                ('Anganwadi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
                ('pwomen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pwomenfoodservice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfoodservice')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_healthtips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_title', models.CharField(max_length=100, null=True)),
                ('tips_description', models.CharField(max_length=300, null=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_foodstockrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsrequest_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
                ('f_status', models.CharField(max_length=100, null=True)),
                ('dofficer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_foodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_stock', models.IntegerField(null=True)),
                ('foodstock_date', models.DateField(max_length=100, null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_foodbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodbooking_date', models.DateField(auto_now_add=True)),
                ('foodbooking_status', models.CharField(max_length=300, null=True)),
                ('Anganwadi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userfoodservice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfoodservice')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=300, null=True)),
                ('usertype', models.CharField(max_length=300, null=True)),
                ('pwomen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomens')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300, null=True)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=300, null=True)),
                ('complaint_status', models.CharField(max_length=300, null=True)),
                ('usertype', models.CharField(max_length=300, null=True)),
                ('complainttype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.complainttype')),
                ('pwomen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomens')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_childfoodstockrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsrequest_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
                ('f_status', models.CharField(max_length=100, null=True)),
                ('dofficer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_childfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_stock', models.IntegerField(null=True)),
                ('foodstock_date', models.DateField(max_length=100, null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, null=True)),
                ('child_age', models.CharField(max_length=100, null=True)),
                ('child_image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('child_fathername', models.CharField(max_length=100, null=True)),
                ('child_mothername', models.CharField(max_length=100, null=True)),
                ('child_gender', models.CharField(max_length=100, null=True)),
                ('child_status', models.CharField(max_length=100, null=True)),
                ('birthcertificate', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('child_hname', models.CharField(max_length=100, null=True)),
                ('child_street', models.CharField(max_length=100, null=True)),
                ('child_pin', models.CharField(max_length=100, null=True)),
                ('child_contact', models.CharField(max_length=100, null=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place'),
        ),
        migrations.AddField(
            model_name='districtofficer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location'),
        ),
        migrations.AddField(
            model_name='districtofficer',
            name='prooftype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.prooftype'),
        ),
        migrations.AddField(
            model_name='districtofficer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, null=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anganawadi',
            name='dofficer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer'),
        ),
        migrations.AddField(
            model_name='anganawadi',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location'),
        ),
        migrations.AddField(
            model_name='anganawadi',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place'),
        ),
        migrations.AddField(
            model_name='anganawadi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
